"use client";

import { useState } from "react";
import * as XLSX from "xlsx";
import { Loader2, Upload } from "lucide-react";
import { EXCEL_TO_DB, Company } from "@/lib/types";

export default function UploadZone({
  onParsed,
}: {
  onParsed: (rows: Partial<Company>[]) => Promise<void>;
}) {
  const [dragOver, setDragOver] = useState(false);
  const [uploading, setUploading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const parseFile = async (file: File) => {
    setUploading(true);
    setError(null);
    try {
      const buf = await file.arrayBuffer();
      const wb = XLSX.read(buf, { type: "array" });
      const sheetName = wb.SheetNames.includes("Prospects") ? "Prospects" : wb.SheetNames[0];
      const ws = wb.Sheets[sheetName];
      const rows: any[][] = XLSX.utils.sheet_to_json(ws, { header: 1, defval: "" });
      const headers = rows[0] as string[];
      const dataRows = rows.slice(1).filter((r) => r[0]);

      const parsed: Partial<Company>[] = dataRows.map((r) => {
        const obj: Partial<Company> = { status: "New" };
        headers.forEach((h, i) => {
          const dbField = EXCEL_TO_DB[h];
          if (dbField) {
            (obj as any)[dbField] = r[i] !== undefined ? String(r[i]) : "";
          }
        });
        return obj;
      });

      await onParsed(parsed);
    } catch (e) {
      setError("Couldn't read that file. Make sure you're uploading the .xlsx generated by Claude, with a 'Prospects' sheet.");
    } finally {
      setUploading(false);
    }
  };

  return (
    <div style={{ padding: "80px 28px", display: "flex", justifyContent: "center" }}>
      <div
        onDragOver={(e) => {
          e.preventDefault();
          setDragOver(true);
        }}
        onDragLeave={() => setDragOver(false)}
        onDrop={(e) => {
          e.preventDefault();
          setDragOver(false);
          const file = e.dataTransfer.files?.[0];
          if (file) parseFile(file);
        }}
        style={{
          width: "100%",
          maxWidth: 520,
          border: `1.5px dashed ${dragOver ? "#C9743B" : "#C9BFA5"}`,
          borderRadius: 16,
          padding: "56px 32px",
          textAlign: "center",
          background: dragOver ? "#FFF9F1" : "#FFFDF8",
        }}
      >
        <div style={{ fontSize: 34, marginBottom: 10 }}>🐦</div>
        <div className="fraunces" style={{ fontSize: 20, marginBottom: 8, color: "#232323" }}>
          Import the prospect spreadsheet
        </div>
        <div style={{ fontSize: 13, color: "#8A8471", marginBottom: 24, lineHeight: 1.5 }}>
          The Excel file (with a "Prospects" sheet). This adds new companies to the shared board — everyone on the
          team will see them.
        </div>
        <label
          style={{
            background: "#232323",
            color: "#F6F3EC",
            border: "none",
            borderRadius: 8,
            padding: "11px 22px",
            fontSize: 13,
            fontWeight: 600,
            display: "inline-flex",
            alignItems: "center",
            gap: 8,
            cursor: "pointer",
          }}
        >
          {uploading ? <Loader2 size={14} style={{ animation: "spin 0.8s linear infinite" }} /> : <Upload size={14} />}
          {uploading ? "Reading..." : "Choose .xlsx file"}
          <input type="file" accept=".xlsx,.xls" style={{ display: "none" }} onChange={(e) => e.target.files?.[0] && parseFile(e.target.files[0])} />
        </label>
        {error && (
          <div style={{ marginTop: 16, color: "#8A2E2E", fontSize: 12, background: "#F1DEDD", padding: "8px 12px", borderRadius: 8 }}>{error}</div>
        )}
      </div>
    </div>
  );
}
