export type Company = {
  id: string;
  company: string;
  website: string | null;
  linkedin: string | null;
  industry: string | null;
  employees: string | null;
  location: string | null;
  hiring_roles: string | null;
  buying_signal: string | null;
  opportunity_summary: string | null;
  fit: string | null;
  decision_maker: string | null;
  title: string | null;
  phone: string | null;
  phone_confidence: string | null;
  email: string | null;
  email_confidence: string | null;
  linkedin_profile: string | null;
  job_posting_url: string | null;
  research_source: string | null;
  research_notes: string | null;
  status: string;
  assignee_email: string | null;
  follow_up_date: string | null;
  source: string;
  created_at: string;
  updated_at: string;
};

export type Note = {
  id: string;
  company_id: string;
  author_email: string;
  text: string;
  created_at: string;
  edited_at: string | null;
};

export type Profile = {
  id: string;
  email: string;
  created_at: string;
};

export type ActivityAction =
  | "created"
  | "field_updated"
  | "status_changed"
  | "fit_changed"
  | "assignee_changed"
  | "note_added"
  | "note_edited"
  | "note_deleted";

export type ActivityLogEntry = {
  id: string;
  company_id: string;
  actor_email: string | null;
  action: ActivityAction;
  field_name: string | null;
  old_value: string | null;
  new_value: string | null;
  created_at: string;
};

export const FIELD_LABELS: Record<string, string> = {
  company: "company name",
  website: "website",
  linkedin: "LinkedIn",
  industry: "industry",
  employees: "employee count",
  location: "location",
  hiring_roles: "hiring roles",
  buying_signal: "buying signal",
  opportunity_summary: "opportunity summary",
  decision_maker: "decision maker",
  title: "contact title",
  phone: "phone",
  phone_confidence: "phone confidence",
  email: "email",
  email_confidence: "email confidence",
  linkedin_profile: "contact's LinkedIn",
  job_posting_url: "job posting URL",
  research_source: "research source",
  research_notes: "research notes",
  follow_up_date: "follow-up date",
};

function truncate(value: string | null, max = 60) {
  if (!value) return "(empty)";
  return value.length > max ? value.slice(0, max) + "…" : value;
}

// Human-readable one-liner for an activity log entry, e.g. "changed Fit from Medium Fit to High Fit".
export function describeActivity(entry: ActivityLogEntry) {
  switch (entry.action) {
    case "created":
      return `added this company (${entry.new_value || "no name"})`;
    case "status_changed":
      return `changed status from ${entry.old_value || "New"} to ${entry.new_value}`;
    case "fit_changed":
      return `changed Fit from ${entry.old_value || "unset"} to ${entry.new_value || "unset"}`;
    case "assignee_changed":
      return entry.new_value ? `assigned this to ${entry.new_value}` : `unassigned this (was ${entry.old_value})`;
    case "field_updated": {
      const label = FIELD_LABELS[entry.field_name || ""] || entry.field_name || "a field";
      return `updated ${label} to "${truncate(entry.new_value)}"`;
    }
    case "note_added":
      return `added a note: "${truncate(entry.new_value)}"`;
    case "note_edited":
      return `edited a note to: "${truncate(entry.new_value)}"`;
    case "note_deleted":
      return `deleted a note: "${truncate(entry.old_value)}"`;
    default:
      return entry.action;
  }
}

export const SIGNUP_EMAIL_DOMAIN = "getbluebirdsolutions.com";

// Days since a row was last touched before we call it "stale" in the UI.
export const STALE_AFTER_DAYS = 14;

export const STATUSES = ["New", "Contacted", "In Progress", "Qualified", "Not Interested", "Closed"] as const;

export const FIT_STYLES: Record<string, { bg: string; fg: string; dot: string }> = {
  "High Fit": { bg: "#E4EDE6", fg: "#2F5233", dot: "#4A7C59" },
  "Medium Fit": { bg: "#F3ECD9", fg: "#7A5C1E", dot: "#C99A3B" },
  "Low-Medium Fit": { bg: "#F1E4D9", fg: "#8A4E2A", dot: "#C9743B" },
  "Low Fit": { bg: "#F1DEDD", fg: "#8A2E2E", dot: "#B84C4C" },
};

export const STATUS_STYLES: Record<string, { bg: string; fg: string }> = {
  New: { bg: "#E9E4F5", fg: "#4B3B7A" },
  Contacted: { bg: "#DDEAF3", fg: "#245577" },
  "In Progress": { bg: "#F3ECD9", fg: "#7A5C1E" },
  Qualified: { bg: "#E4EDE6", fg: "#2F5233" },
  "Not Interested": { bg: "#EDEAE0", fg: "#6B6656" },
  Closed: { bg: "#F1DEDD", fg: "#8A2E2E" },
};

// Maps the Excel column header (as generated by Claude) to the DB column name
export const EXCEL_TO_DB: Record<string, keyof Company> = {
  "Company": "company",
  "Website": "website",
  "LinkedIn": "linkedin",
  "Industry": "industry",
  "Employees": "employees",
  "Location": "location",
  "Hiring Roles": "hiring_roles",
  "Buying Signal": "buying_signal",
  "Opportunity Intelligence Summary": "opportunity_summary",
  "Fit": "fit",
  "Decision Maker": "decision_maker",
  "Title": "title",
  "Phone": "phone",
  "Phone Confidence": "phone_confidence",
  "Email": "email",
  "Email Confidence": "email_confidence",
  "LinkedIn Profile": "linkedin_profile",
  "Job Posting URL": "job_posting_url",
  "Research Source": "research_source",
  "Notes": "research_notes",
};

export function isDNC(phone: string | null | undefined) {
  return typeof phone === "string" && phone.toUpperCase().includes("DO NOT CALL");
}

export function cleanPhoneDisplay(phone: string | null | undefined) {
  if (!phone) return "";
  const parts = phone.split("—");
  return parts.length > 1 ? parts[1].trim() : phone;
}

// Short relative age (e.g. "3d", "5w", "2mo", "1y") for the "added" column,
// plus a full date string for the tooltip.
export function formatAge(dateStr: string) {
  const then = new Date(dateStr).getTime();
  const days = Math.max(0, Math.floor((Date.now() - then) / (1000 * 60 * 60 * 24)));
  let short: string;
  if (days === 0) short = "Today";
  else if (days < 7) short = `${days}d`;
  else if (days < 30) short = `${Math.floor(days / 7)}w`;
  else if (days < 365) short = `${Math.floor(days / 30)}mo`;
  else short = `${Math.floor(days / 365)}y`;
  const full = new Date(dateStr).toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric" });
  return { short, full, days };
}

// Follow-up dates are stored as plain "YYYY-MM-DD" (no time), so compare at the day level.
export function isOverdue(followUpDate: string | null | undefined) {
  if (!followUpDate) return false;
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  return new Date(followUpDate + "T00:00:00") < today;
}

// Everyone shares the same email domain, so the part before "@" is enough to identify a teammate
// in tight UI spots (dropdowns, table cells) — full email stays in the value/title for clarity.
export function emailLocalPart(email: string) {
  return email.split("@")[0];
}

// Research data often stores URLs without a protocol (e.g. "acmehealth.com"). Used bare as an
// <a href>, that's a relative link and opens under the current page instead of the real site.
export function normalizeUrl(url: string) {
  return /^https?:\/\//i.test(url) ? url : `https://${url}`;
}

export function isStale(updatedAt: string) {
  const days = Math.floor((Date.now() - new Date(updatedAt).getTime()) / (1000 * 60 * 60 * 24));
  return days >= STALE_AFTER_DAYS;
}
