export type Company = {
  id: string;
  company: string;
  website: string | null;
  linkedin: string | null;
  industry: string | null;
  employees: string | null;
  location: string | null;
  hiring_roles: string | null;
  buying_signal: string | null;
  opportunity_summary: string | null;
  fit: string | null;
  decision_maker: string | null;
  title: string | null;
  phone: string | null;
  phone_confidence: string | null;
  email: string | null;
  email_confidence: string | null;
  linkedin_profile: string | null;
  job_posting_url: string | null;
  research_source: string | null;
  research_notes: string | null;
  status: string;
  assignee_email: string | null;
  created_at: string;
  updated_at: string;
};

export type Note = {
  id: string;
  company_id: string;
  author_email: string;
  text: string;
  created_at: string;
  edited_at: string | null;
};

export const STATUSES = ["New", "Contacted", "In Progress", "Qualified", "Not Interested", "Closed"] as const;

export const FIT_STYLES: Record<string, { bg: string; fg: string; dot: string }> = {
  "High Fit": { bg: "#E4EDE6", fg: "#2F5233", dot: "#4A7C59" },
  "Medium Fit": { bg: "#F3ECD9", fg: "#7A5C1E", dot: "#C99A3B" },
  "Low-Medium Fit": { bg: "#F1E4D9", fg: "#8A4E2A", dot: "#C9743B" },
  "Low Fit": { bg: "#F1DEDD", fg: "#8A2E2E", dot: "#B84C4C" },
};

export const STATUS_STYLES: Record<string, { bg: string; fg: string }> = {
  New: { bg: "#E9E4F5", fg: "#4B3B7A" },
  Contacted: { bg: "#DDEAF3", fg: "#245577" },
  "In Progress": { bg: "#F3ECD9", fg: "#7A5C1E" },
  Qualified: { bg: "#E4EDE6", fg: "#2F5233" },
  "Not Interested": { bg: "#EDEAE0", fg: "#6B6656" },
  Closed: { bg: "#F1DEDD", fg: "#8A2E2E" },
};

// Maps the Excel column header (as generated by Claude) to the DB column name
export const EXCEL_TO_DB: Record<string, keyof Company> = {
  "Company": "company",
  "Website": "website",
  "LinkedIn": "linkedin",
  "Industry": "industry",
  "Employees": "employees",
  "Location": "location",
  "Hiring Roles": "hiring_roles",
  "Buying Signal": "buying_signal",
  "Opportunity Intelligence Summary": "opportunity_summary",
  "Fit": "fit",
  "Decision Maker": "decision_maker",
  "Title": "title",
  "Phone": "phone",
  "Phone Confidence": "phone_confidence",
  "Email": "email",
  "Email Confidence": "email_confidence",
  "LinkedIn Profile": "linkedin_profile",
  "Job Posting URL": "job_posting_url",
  "Research Source": "research_source",
  "Notes": "research_notes",
};

export function isDNC(phone: string | null | undefined) {
  return typeof phone === "string" && phone.toUpperCase().includes("DO NOT CALL");
}

export function cleanPhoneDisplay(phone: string | null | undefined) {
  if (!phone) return "";
  const parts = phone.split("—");
  return parts.length > 1 ? parts[1].trim() : phone;
}
